# Generated by Django 3.2.7 on 2022-03-04 04:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0002_auto_20220304_0956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='closed',
            new_name='closTime',
        ),
        migrations.AddField(
            model_name='order',
            name='openTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='opened',
            field=models.BooleanField(),
        ),
    ]
