# Generated by Django 3.2.7 on 2022-03-04 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0003_auto_20220304_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='closTime',
            new_name='closeTime',
        ),
    ]
